name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Node JS Setup
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - name: Install
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run test
